export class Home {
  static readonly moduleName: string = "home"
  static readonly HomePage: string = "HomePage"
}

export class Square {
  static readonly moduleName: string = "square"
  static readonly SquarePage: string = "SquarePage"
}

export class User {
  static readonly moduleName: string = "user"
  static readonly MinePage: string = "MinePage"
}

export class Find {
  static readonly moduleName: string = "find"
  static readonly FindPage: string = "FindPage"
}
